#!/usr/bin/env rv run ruby
require_relative "common"
require_relative "config"

module WorktreeTools
  class CaddyDev
    include Helpers

    def initialize(config, path = ".")
      @config = config
      @path = Pathname.new(File.expand_path(path))
    end

    def setup!
      return unless @config.caddy_enabled?

      hostname = build_hostname
      port = @config.calculated_port(@path)
      config_file = caddy_file_path(hostname)

      log "Setting up Caddy..."
      log "  URL: https://#{hostname}"
      log "  Port: #{port}"

      ensure_directory(Pathname.new(@config.caddy_config_dir))
      File.write(config_file, render(hostname, port))
      reload_caddy

      log "Caddy setup complete"
    end

    def remove!
      return unless @config.caddy_enabled?

      hostname = build_hostname
      config_file = caddy_file_path(hostname)

      if File.exist?(config_file)
        log "Removing Caddy config: #{File.basename(config_file)}"
        File.delete(config_file)
        reload_caddy
        log "Caddy config removed"
      end
    end

    private

    def build_hostname
      if main_hostname?
        "#{@config.caddy_project_name}.#{@config.caddy_tld}"
      else
        "#{@config.caddy_name}.#{@config.caddy_project_name}.#{@config.caddy_tld}"
      end
    end

    def main_hostname?
      @config.caddy_name == @config.caddy_project_name || @config.caddy_name == "main"
    end

    def caddy_file_path(hostname)
      File.join(@config.caddy_config_dir, "worktree-#{hostname}.caddy")
    end

    def render(hostname, port)
      tls_line = if @config.caddy_tls_cert && @config.caddy_tls_key
        "tls #{@config.caddy_tls_cert} #{@config.caddy_tls_key}"
      else
        "tls internal"
      end

      <<~CADDY
        # Auto-generated by worktree-setup. Do not edit manually.
        #{hostname} {
          #{tls_line}
          reverse_proxy http://127.0.0.1:#{port} {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
          }
        }
      CADDY
    end

    def reload_caddy
      return unless command_exists?("caddy")

      caddyfile = find_caddyfile
      return unless caddyfile

      _output, status = Open3.capture2("caddy", "reload", "--config", caddyfile)
      warn "Failed to reload Caddy - you may need to reload manually" unless status.success?
    end

    def find_caddyfile
      [
        File.expand_path("~/.config/caddy/Caddyfile"),
        "/etc/caddy/Caddyfile",
        "/usr/local/etc/caddy/Caddyfile",
        "/opt/homebrew/etc/caddy/Caddyfile"
      ].find { |f| File.exist?(f) }
    end
  end
end
