#!/usr/bin/env rv run ruby
require_relative "common"
require_relative "config"

module WorktreeTools
  class CaddyDev
    include Helpers
    MARKER_PREFIX = "worktree-tools:source_path=".freeze

    def initialize(config, path = ".")
      @config = config
      @path = Pathname.new(File.expand_path(path))
    end

    def setup!
      return unless @config.caddy_enabled?

      hostname = build_hostname
      port = @config.calculated_port(@path)
      config_file = caddy_file_path(hostname)

      log "Setting up Caddy..."
      log "  URL: https://#{hostname}"
      log "  Port: #{port}"

      ensure_directory(Pathname.new(@config.caddy_config_dir))
      File.write(config_file, render(hostname, port, worktree_source_path))
      reload_caddy

      log "Caddy setup complete"
    end

    def remove!
      removed_files = remove_generated_files

      unless removed_files.empty?
        reload_caddy
        log "Caddy config removed"
      end
    end

    private

    def build_hostname
      if main_hostname?
        "#{@config.caddy_project_name}.#{@config.caddy_tld}"
      else
        "#{@config.caddy_name}.#{@config.caddy_project_name}.#{@config.caddy_tld}"
      end
    end

    def main_hostname?
      @config.caddy_name == @config.caddy_project_name || @config.caddy_name == "main"
    end

    def caddy_file_path(hostname)
      File.join(@config.caddy_config_dir, "worktree-#{hostname}.caddy")
    end

    def render(hostname, port, source_path)
      tls_line = if @config.caddy_tls_cert && @config.caddy_tls_key
        "tls #{@config.caddy_tls_cert} #{@config.caddy_tls_key}"
      else
        "tls internal"
      end

      <<~CADDY
        # Auto-generated by worktree-setup. Do not edit manually.
        # #{MARKER_PREFIX}#{source_path}
        #{hostname} {
          #{tls_line}
          reverse_proxy http://127.0.0.1:#{port} {
            header_up Host {host}
            header_up X-Forwarded-Proto {scheme}
          }
        }
      CADDY
    end

    def reload_caddy
      return unless command_exists?("caddy")

      caddyfile = find_caddyfile
      return unless caddyfile

      _output, status = Open3.capture2("caddy", "reload", "--config", caddyfile)
      warn "Failed to reload Caddy - you may need to reload manually" unless status.success?
    end

    def find_caddyfile
      [
        File.expand_path("~/.config/caddy/Caddyfile"),
        "/etc/caddy/Caddyfile",
        "/usr/local/etc/caddy/Caddyfile",
        "/opt/homebrew/etc/caddy/Caddyfile"
      ].find { |f| File.exist?(f) }
    end

    def remove_generated_files
      files_to_remove = generated_files_for_worktree
      files_to_remove << caddy_file_path(build_hostname)
      files_to_remove.uniq!

      files_to_remove.each_with_object([]) do |file_path, removed_files|
        next unless File.exist?(file_path)

        log "Removing Caddy config: #{File.basename(file_path)}"
        File.delete(file_path)
        removed_files << file_path
      end
    end

    def generated_files_for_worktree
      config_dir = @config.caddy_config_dir
      return [] unless config_dir && Dir.exist?(config_dir)

      marker = "# #{MARKER_PREFIX}#{worktree_source_path}"
      Dir.glob(File.join(config_dir, "worktree-*.caddy")).select do |file_path|
        File.read(file_path).include?(marker)
      rescue StandardError
        false
      end
    end

    def worktree_source_path
      @path.realpath.to_s
    rescue StandardError
      @path.to_s
    end
  end
end
