require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - db/**/*schema.rb
    - db/schema.rb
    - bin/**/*
    - node_modules/**/*
  NewCops: enable ## Cops that need decisions are enabled by default

# Layout
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: true
Layout/EndAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyleAlignWith: keyword
  Severity: warning
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned
  IndentationWidth: ~

# Metrics
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/MethodLength:
  Max: 20

# Style
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false



