inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-obsession
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  SuggestExtensions: true

  Exclude:
    - '**/app/assets/**/*'
    - '**/db/**/*schema.rb'
    - '**/db/schema.rb'
    - '**/log/**/*'
    - '**/node_modules/**/*'
    - '**/public/**/*'
    - '**/storage/**/*'
    - '**/templates/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - 'actionmailbox/test/dummy/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actiontext/test/dummy/**/*'
    - 'bin/**/*'

  NewCops: enable ## Cops that need decisions are enabled by default

# Metrics
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# Extensions
## Minitest
Minitest/UnreachableAssertion:
  Enabled: true

## Rails
Rails/AssertNot: # Prefer assert_not over assert !
  Include:
    - '**/test/**/*'
Rails/RefuteMethods: # Prefer assert_not_x over refute_x
  Include:
    - '**/test/**/*'
Rails/IndexBy:
  Enabled: true
Rails/IndexWith:
  Enabled: true

## Performance
Performance/BindCall:
  Enabled: true
Performance/DeletePrefix:
  Enabled: true
Performance/DeleteSuffix:
  Enabled: true
Performance/EndWith:
  Enabled: true
Performance/FlatMap:
  Enabled: true
Performance/MapCompact:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/RegexpMatch:
  Enabled: true
Performance/ReverseEach:
  Enabled: true
Performance/SelectMap:
  Enabled: true
Performance/StartWith:
  Enabled: true
Performance/StringReplacement:
  Enabled: true
Performance/UnfreezeString:
  Enabled: true

