#!/usr/bin/env bash
if command -v scss-lint > /dev/null; then
  echo "Running scss-lint on staged CSS files"
  git status --porcelain \
  | grep -E '^A|^M' \
  | grep -E '\.scss|\.css' \
  | awk '{print $2}' \
  | xargs -r scss-lint
fi
