#!/usr/bin/env bash
# Package installation steps driven by generated Brewfiles and Flatpakfile,
# plus additional “brew-first, native-fallback” lists from packages.conf.
#
# This file is intended to be sourced by `install.sh` after:
# - OS has been detected (determine_os -> $OS)
# - Homebrew is installed and `setup_brew_shellenv` has been run
# - OS-specific prereqs have been ensured
# - packages.conf has been been sourced (optional lists may exist)
#
# Install policy:
# - Prefer Homebrew across all OSes.
# - Fall back to native package managers only when Homebrew cannot install a given package.
# - Install macOS casks only on macOS.
# - Install Flatpaks only on non-macOS (when flatpak is available).
# - Brewfiles in dotfiles/brewfiles/* are generated by save.sh and may be overwritten.
#
# IMPORTANT:
# - Some Homebrew installs may add binaries that are not immediately available in the current shell
#   until `brew shellenv` is re-evaluated. We refresh shellenv after bundle runs.

set -euo pipefail

BREWFILES_DIR="${BREWFILES_DIR:-brew}"
BREWFILE_FORMULAE="${BREWFILE_FORMULAE:-${BREWFILES_DIR}/Brewfile.formulae}"
BREWFILE_CASKS="${BREWFILE_CASKS:-${BREWFILES_DIR}/Brewfile.casks}"
BREWFILE_VSCODE="${BREWFILE_VSCODE:-${BREWFILES_DIR}/Brewfile.vscode}"
FLATPAKFILE="${FLATPAKFILE:-${BREWFILES_DIR}/Flatpakfile}"

check_brew_ready() {
  check_required_tooling brew
}

refresh_brew_shellenv() {
  # Ensure any newly installed brew binaries are available to subsequent steps.
  setup_brew_shellenv
}

brew_bundle_file() {
  local file="$1"

  [[ -f "$file" ]] || abort "Brewfile not found: $file"

  # Homebrew Bundle lives at `brew bundle`. This will install taps + entries.
  # We keep it non-interactive and idempotent.
  log "Installing from Brewfile: $file"
  brew bundle --file="$file"

  refresh_brew_shellenv
}

install_brew_formulae() {
  check_brew_ready
  brew_bundle_file "$BREWFILE_FORMULAE"
}

install_brew_casks_if_macos() {
  check_brew_ready

  if [[ "${OS:-Unknown}" != "macOS" ]]; then
    log "Skipping casks (OS=${OS:-Unknown})"
    return 0
  fi

  brew_bundle_file "$BREWFILE_CASKS"
}

install_vscode_extensions_if_available() {
  check_brew_ready

  # Homebrew Bundle supports `vscode` entries if VS Code is installed and/or the
  # extension manager is available. This can be a noop if not present.
  if [[ ! -f "$BREWFILE_VSCODE" ]]; then
    log "Skipping VS Code extensions (missing: $BREWFILE_VSCODE)"
    return 0
  fi

  log "Installing VS Code extensions from: $BREWFILE_VSCODE"
  brew bundle --file="$BREWFILE_VSCODE" || warn "VS Code extension install step failed; continuing."
}

flatpak_is_available() {
  need_cmd flatpak
}

flatpakfile_install() {
  local file="$1"

  [[ -f "$file" ]] || abort "Flatpakfile not found: $file"
  flatpak_is_available || abort "flatpak not found; cannot install Flatpak packages."

  log "Ensuring Flathub remote exists…"
  # Use --user to avoid root and keep it user-space (align with brew philosophy).
  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  log "Installing Flatpak refs from: $file"
  # Read lines of form: "<remote> <ref>" (e.g. "flathub com.discordapp.Discord")
  # Ignore blank lines and comments.
  while IFS= read -r line; do
    # Strip leading/trailing whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"

    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue

    # Split into remote + ref. If only a ref is provided, assume flathub.
    local remote ref
    remote="$(printf '%s' "$line" | awk '{print $1}')"
    ref="$(printf '%s' "$line" | awk '{print $2}')"

    if [[ -z "$ref" ]]; then
      ref="$remote"
      remote="flathub"
    fi

    log "Installing Flatpak: ${remote} ${ref}"
    flatpak install --user --noninteractive --or-update "$remote" "$ref"
  done <"$file"
}

install_flatpaks_if_non_macos() {
  if [[ "${OS:-Unknown}" == "macOS" ]]; then
    log "Skipping Flatpaks on macOS."
    return 0
  fi

  if [[ ! -f "$FLATPAKFILE" ]]; then
    log "Skipping Flatpaks (missing: $FLATPAKFILE)"
    return 0
  fi

  if ! flatpak_is_available; then
    warn "flatpak is not installed; skipping Flatpak packages."
    return 0
  fi

  flatpakfile_install "$FLATPAKFILE"
}

install_packages_from_array_via_brew_or_native() {
  # Installs packages by name using the global policy function:
  #   install_via_brew_or_native <pkg>
  #
  # This requires:
  # - brew to be available (already set up by install.sh)
  # - OS-specific native fallback functions to exist (loaded by install.sh)
  local array_name="$1"

  if [[ -z "$array_name" ]]; then
    abort "install_packages_from_array_via_brew_or_native requires an array name"
  fi

  # Ensure the array exists before trying to indirect expand it.
  if ! declare -p "$array_name" >/dev/null 2>&1; then
    return 0
  fi

  log "Installing packages from ${array_name} (brew-first, native fallback)…"

  local pkg
  # shellcheck disable=SC1087,SC2086
  eval "for pkg in \"\${${array_name}[@]}\"; do
    [[ -z \"\$pkg\" ]] && continue
    install_via_brew_or_native \"\$pkg\"
  done"
}

install_brew_only_packages_if_macos() {
  if [[ "${OS:-Unknown}" != "macOS" ]]; then
    return 0
  fi

  if ! declare -p BREW_ONLY >/dev/null 2>&1; then
    return 0
  fi

  log "Installing BREW_ONLY packages on macOS…"
  local pkg
  for pkg in "${BREW_ONLY[@]}"; do
    [[ -z "$pkg" ]] && continue
    install_via_brew_or_native "$pkg"
  done
}

install_native_only_packages_if_applicable() {
  # These lists are explicitly native-only by definition. We still run them
  # through `install_via_brew_or_native` so you get “brew-first” behavior if you
  # accidentally put a brew-available package into a native-only list.
  case "${OS:-Unknown}" in
    SteamOS)
      install_packages_from_array_via_brew_or_native "PACMAN_ONLY"
      ;;
    Debian)
      install_packages_from_array_via_brew_or_native "APT_ONLY"
      ;;
  esac
}

install_os_routed_packages() {
  # “Install everywhere” list that uses the brew-first/native-fallback policy.
  install_packages_from_array_via_brew_or_native "OS_ROUTED"
}

install_all_packages_from_files() {
  # Primary package installation pipeline. Adjust ordering as needed.
  install_brew_formulae
  install_brew_casks_if_macos
  install_vscode_extensions_if_available
  install_flatpaks_if_non_macos

  # Additional policy-driven lists from packages.conf
  install_os_routed_packages
  install_brew_only_packages_if_macos
  install_native_only_packages_if_applicable
}
