-- Solunized colorscheme for Neovim
-- Auto-generated by generate_themes.rb — do not edit by hand.
-- https://github.com/solunized

local palettes = {
  ["dark"] = {
    bg_0         = "#012b38",
    bg_1         = "#0d3b4a",
    bg_2         = "#2a5d6e",
    dim_0        = "#5e8c96",
    fg_0         = "#b0d0d5",
    fg_1         = "#cce2e7",
    red          = "#f7564f",
    green        = "#73b936",
    yellow       = "#d9b02a",
    blue         = "#4191f4",
    magenta      = "#f072bb",
    cyan         = "#3fc4b6",
    orange       = "#ea8347",
    violet       = "#ac85e8",
    br_red       = "#ff6a60",
    br_green     = "#81c745",
    br_yellow    = "#e8be39",
    br_blue      = "#56a0fc",
    br_magenta   = "#fd81cc",
    br_cyan      = "#51d4c4",
    br_orange    = "#fa9253",
    br_violet    = "#ba93f7",
  },
  ["light"] = {
    bg_0         = "#fffbf1",
    bg_1         = "#eeeae0",
    bg_2         = "#d5d2c8",
    dim_0        = "#6a8990",
    fg_0         = "#243f47",
    fg_1         = "#10232c",
    red          = "#c51f23",
    green        = "#398300",
    yellow       = "#906e00",
    blue         = "#0068c9",
    magenta      = "#bc4090",
    cyan         = "#00817a",
    orange       = "#b05015",
    violet       = "#795bc0",
    br_red       = "#b81a1e",
    br_green     = "#337700",
    br_yellow    = "#826100",
    br_blue      = "#005fc0",
    br_magenta   = "#b23886",
    br_cyan      = "#007770",
    br_orange    = "#a44910",
    br_violet    = "#6e52b5",
  },
  ["black"] = {
    bg_0         = "#0a1214",
    bg_1         = "#14212a",
    bg_2         = "#253a42",
    dim_0        = "#57727a",
    fg_0         = "#9ab6bc",
    fg_1         = "#b8cdd1",
    red          = "#f7564f",
    green        = "#73b936",
    yellow       = "#d9b02a",
    blue         = "#4191f4",
    magenta      = "#f072bb",
    cyan         = "#3fc4b6",
    orange       = "#ea8347",
    violet       = "#ac85e8",
    br_red       = "#ff6a60",
    br_green     = "#81c745",
    br_yellow    = "#e8be39",
    br_blue      = "#56a0fc",
    br_magenta   = "#fd81cc",
    br_cyan      = "#51d4c4",
    br_orange    = "#fa9253",
    br_violet    = "#ba93f7",
  },
  ["white"] = {
    bg_0         = "#fafcfd",
    bg_1         = "#ebf2f4",
    bg_2         = "#cddce0",
    dim_0        = "#6b8d95",
    fg_0         = "#354f57",
    fg_1         = "#1d3740",
    red          = "#c51f23",
    green        = "#398300",
    yellow       = "#906e00",
    blue         = "#0068c9",
    magenta      = "#bc4090",
    cyan         = "#00817a",
    orange       = "#b05015",
    violet       = "#795bc0",
    br_red       = "#b81a1e",
    br_green     = "#337700",
    br_yellow    = "#826100",
    br_blue      = "#005fc0",
    br_magenta   = "#b23886",
    br_cyan      = "#007770",
    br_orange    = "#a44910",
    br_violet    = "#6e52b5",
  },
}

local function get_variant()
  if vim.o.background == "dark" then
    if vim.g.solunized_dark_variant == "black" then return "black" end
    return "dark"
  else
    if vim.g.solunized_light_variant == "white" then return "white" end
    return "light"
  end
end

local p = palettes[get_variant()]

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "solunized"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base
hi("Normal",            { fg = p.fg_1,    bg = p.bg_0 })
hi("NormalFloat",       { fg = p.fg_1,    bg = p.bg_1 })
hi("NormalNC",          { fg = p.fg_0,    bg = p.bg_0 })
hi("NormalSB",          { fg = p.fg_0,    bg = p.bg_1 })

-- Syntax
hi("Comment",           { fg = p.dim_0,   italic = true })
hi("Constant",          { fg = p.cyan })
hi("String",            { fg = p.cyan })
hi("Character",         { fg = p.cyan })
hi("Number",            { fg = p.cyan })
hi("Boolean",           { fg = p.cyan })
hi("Float",             { fg = p.cyan })
hi("Identifier",        { fg = p.blue })
hi("Function",          { fg = p.blue })
hi("Statement",         { fg = p.dim_0,   bold = true, italic = true })
hi("Conditional",       { fg = p.dim_0,   bold = true, italic = true })
hi("Repeat",            { fg = p.dim_0,   bold = true, italic = true })
hi("Label",             { fg = p.dim_0,   bold = true, italic = true })
hi("Operator",          { fg = p.dim_0 })
hi("Keyword",           { fg = p.dim_0,   bold = true, italic = true })
hi("Exception",         { fg = p.dim_0,   bold = true, italic = true })
hi("PreProc",           { fg = p.orange })
hi("Include",           { fg = p.orange })
hi("Define",            { fg = p.orange })
hi("Macro",             { fg = p.orange })
hi("PreCondit",         { fg = p.orange })
hi("Type",              { fg = p.orange })
hi("StorageClass",      { fg = p.orange })
hi("Structure",         { fg = p.orange })
hi("Typedef",           { fg = p.orange })
hi("Special",           { fg = p.red })
hi("SpecialChar",       { fg = p.red })
hi("Tag",               { fg = p.green })
hi("Delimiter",         { fg = p.dim_0 })
hi("SpecialComment",    { fg = p.dim_0,   italic = true })
hi("Debug",             { fg = p.red })
hi("Underlined",        { fg = p.blue,    underline = true })
hi("Error",             { fg = p.br_red,  bold = true })
hi("Todo",              { fg = p.yellow,  bold = true })

-- Editor UI
hi("LineNr",            { fg = p.bg_2 })
hi("CursorLineNr",      { fg = p.dim_0 })
hi("CursorLine",        { bg = p.bg_1 })
hi("CursorColumn",      { bg = p.bg_1 })
hi("ColorColumn",       { bg = p.bg_1 })
hi("SignColumn",        { fg = p.dim_0,   bg = p.bg_0 })
hi("Folded",            { fg = p.dim_0,   bg = p.bg_1 })
hi("FoldColumn",        { fg = p.bg_2,    bg = p.bg_0 })
hi("VertSplit",         { fg = p.bg_2 })
hi("WinSeparator",      { fg = p.bg_2 })
hi("StatusLine",        { fg = p.fg_0,    bg = p.bg_1 })
hi("StatusLineNC",      { fg = p.dim_0,   bg = p.bg_1 })
hi("Pmenu",             { fg = p.fg_0,    bg = p.bg_1 })
hi("PmenuSel",          { fg = p.fg_1,    bg = p.bg_2 })
hi("PmenuSbar",         { bg = p.bg_2 })
hi("PmenuThumb",        { bg = p.dim_0 })
hi("TabLine",           { fg = p.dim_0,   bg = p.bg_1 })
hi("TabLineSel",        { fg = p.fg_1,    bg = p.bg_0 })
hi("TabLineFill",       { bg = p.bg_1 })
hi("Visual",            { bg = p.bg_2 })
hi("VisualNOS",         { bg = p.bg_2 })
hi("Search",            { fg = p.bg_0,    bg = p.yellow })
hi("IncSearch",         { fg = p.bg_0,    bg = p.br_yellow })
hi("CurSearch",         { fg = p.bg_0,    bg = p.br_yellow })
hi("WildMenu",          { fg = p.fg_1,    bg = p.bg_2 })
hi("Directory",         { fg = p.blue })
hi("Title",             { fg = p.blue,    bold = true })
hi("DiffAdd",           { fg = p.br_green })
hi("DiffChange",        { fg = p.br_yellow })
hi("DiffDelete",        { fg = p.red })
hi("DiffText",          { fg = p.br_yellow, bold = true })
hi("SpellBad",          { undercurl = true, sp = p.red })
hi("SpellCap",          { undercurl = true, sp = p.yellow })
hi("SpellRare",         { undercurl = true, sp = p.magenta })
hi("SpellLocal",        { undercurl = true, sp = p.cyan })
hi("NonText",           { fg = p.bg_2 })
hi("SpecialKey",        { fg = p.bg_2 })
hi("MatchParen",        { fg = p.br_orange, bold = true })
hi("ErrorMsg",          { fg = p.br_red,  bold = true })
hi("WarningMsg",        { fg = p.yellow })
hi("ModeMsg",           { fg = p.fg_0 })
hi("MoreMsg",           { fg = p.blue })
hi("Question",          { fg = p.blue })
hi("FloatBorder",       { fg = p.bg_2,    bg = p.bg_1 })
hi("FloatTitle",        { fg = p.blue,    bg = p.bg_1 })

-- LSP / Diagnostics
hi("DiagnosticError",             { fg = p.br_red })
hi("DiagnosticWarn",              { fg = p.orange })
hi("DiagnosticInfo",              { fg = p.blue })
hi("DiagnosticHint",              { fg = p.cyan })
hi("DiagnosticUnderlineError",    { undercurl = true, sp = p.br_red })
hi("DiagnosticUnderlineWarn",     { undercurl = true, sp = p.orange })
hi("DiagnosticUnderlineInfo",     { undercurl = true, sp = p.blue })
hi("DiagnosticUnderlineHint",     { undercurl = true, sp = p.cyan })
hi("DiagnosticVirtualTextError",  { fg = p.br_red })
hi("DiagnosticVirtualTextWarn",   { fg = p.orange })
hi("DiagnosticVirtualTextInfo",   { fg = p.blue })
hi("DiagnosticVirtualTextHint",   { fg = p.cyan })

-- Treesitter
hi("@comment",              { link = "Comment" })
hi("@keyword",              { link = "Keyword" })
hi("@keyword.function",     { link = "Keyword" })
hi("@keyword.return",       { link = "Keyword" })
hi("@function",             { link = "Function" })
hi("@function.builtin",     { fg = p.br_blue })
hi("@function.method",      { fg = p.br_blue })
hi("@constructor",          { fg = p.blue })
hi("@type",                 { link = "Type" })
hi("@type.builtin",         { fg = p.orange, italic = true })
hi("@variable",             { fg = p.green })
hi("@variable.builtin",     { fg = p.magenta })
hi("@variable.member",      { fg = p.green })
hi("@property",             { fg = p.green })
hi("@parameter",            { fg = p.green })
hi("@string",               { link = "String" })
hi("@string.regex",         { fg = p.red })
hi("@string.escape",        { fg = p.orange })
hi("@constant",             { link = "Constant" })
hi("@constant.builtin",     { fg = p.cyan })
hi("@operator",             { link = "Operator" })
hi("@punctuation",          { link = "Delimiter" })
hi("@punctuation.bracket",  { fg = p.dim_0 })
hi("@punctuation.delimiter",{ fg = p.dim_0 })
hi("@attribute",            { fg = p.green })
hi("@tag",                  { fg = p.dim_0 })
hi("@tag.attribute",        { fg = p.green, italic = true })
hi("@tag.delimiter",        { fg = p.dim_0 })
hi("@markup.heading",       { fg = p.blue,  bold = true })
hi("@markup.bold",          { bold = true })
hi("@markup.italic",        { italic = true })
hi("@markup.link",          { fg = p.blue,  underline = true })
hi("@markup.raw",           { fg = p.cyan })

-- Terminal colors (ANSI 0–15)
vim.g.terminal_color_0  = p.fg_0
vim.g.terminal_color_1  = p.red
vim.g.terminal_color_2  = p.green
vim.g.terminal_color_3  = p.yellow
vim.g.terminal_color_4  = p.blue
vim.g.terminal_color_5  = p.magenta
vim.g.terminal_color_6  = p.cyan
vim.g.terminal_color_7  = p.dim_0
vim.g.terminal_color_8  = p.fg_1
vim.g.terminal_color_9  = p.br_red
vim.g.terminal_color_10 = p.br_green
vim.g.terminal_color_11 = p.br_yellow
vim.g.terminal_color_12 = p.br_blue
vim.g.terminal_color_13 = p.br_magenta
vim.g.terminal_color_14 = p.br_cyan
vim.g.terminal_color_15 = p.fg_1
