#!/usr/bin/env bash
if command -v erblint > /dev/null; then
  echo "Running ERB Lint on staged ERB files"
  git status --porcelain \
  | grep -E '^A|^M' \
  | grep -E '\.rb' \
  | awk '{print $2}' \
  | xargs -r erblint
fi

# copied over during git init
# from https://mccalljt.io/blog/2017/01/rubocop-pipes/
