#!/usr/bin/env bash
if command -v rubocop > /dev/null; then
  echo "Running rubocop on staged Ruby files"
  git status --porcelain \
  | grep -E '^A|^M' \
  | grep -E '\.rb' \
  | awk '{print $2}' \
  | xargs -r rubocop -c .rubocop.yml
fi

# copied over during git init
# from https://mccalljt.io/blog/2017/01/rubocop-pipes/
